### ISSUE TITLE
Hovering on certain CTA buttons doesn’t show enough contrast for the text

### ISSUE THREAD

**Issue by sssoz** [Vitaliy-1/traditional#23]
See: https://demo.publicknowledgeproject.org/ojs3/demo/index.php/trad/article/view/815

Default: 

<img width="447" alt="screen shot 2018-06-29 at 13 23 21" src="https://user-images.githubusercontent.com/6668406/42105787-b6f1a70a-7b9f-11e8-8dcc-626b99a8cc48.png">

---

Hover:

<img width="410" alt="screen shot 2018-06-29 at 13 23 24" src="https://user-images.githubusercontent.com/6668406/42105786-b6d23654-7b9f-11e8-8e90-d95b5204d62a.png">

**Comment by sssoz** [comment]
@Vitaliy-1 This style seems to be inherited from two stylesheets (`reboot.scss` and `hover.scss`) which are overriding our custom stylesheet! Can you reorder the stylesheets so that this doesn’t happen?

**Comment by Vitaliy-1** [comment]
Our stylesheets are loading after Bootstrap's: https://github.com/Vitaliy-1/traditional/blob/master/TraditionalThemePlugin.inc.php#L24-L26

**Comment by Vitaliy-1** [comment]
@sssoz Done here.
